name = "DrakanHex"
author = "alexyzer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff4b96048735e9dbe98c8ecafb119aefa59503da1230f0bf0f6341466fee8138"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
