name = "DrakanHex"
author = "alexyzer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb0f283b0d9e41a47fc0e593b6ee085cfdc31ed4011b4e00638f65889b6dfe5a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
