name = "DrakanHex"
author = "alexyzer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3b757a77248dd83ce08b4b4d914795329b93ceaed21eced37a192db428edab3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
